; PlatformIO Project Configuration File
; Project: Precision RF Generator / GPSDO (Si5351A + Arduino Nano + NEO-6M)

[platformio]
src_dir = .
include_dir = .
default_envs = nanoatmega328

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 115200

lib_deps =
    etherkit/Etherkit Si5351 @ ^2.2.0

[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200

lib_deps =
    etherkit/Etherkit Si5351 @ ^2.2.0
